name: "Building test"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: workflow/nix-shell-action@v3
      with:
        flakes-from-devshell: true

    - name: Check if flake files are formatted
      run: make format-check

    - name: Check if flake files are syntactically correct
      run: make check

    - name: Build base CDDA game with basic mods (#extras)
      run: nix build .#extras

    - name: Print all the post-build extra installed content directories
      run: |
        echo
        echo "MODs"
        echo "------------------------------"
        ls "$(readlink -f result)/data/mods"

        echo
        echo "SOUNDs"
        echo "------------------------------"
        ls "$(readlink -f result)/data/sound"

        echo
        echo "GFXs"
        echo "-----------------------------"
        ls "$(readlink -f result)/gfx"

    - name: Show the internal build log of the flake
      run: nix log .#extras | cat
