name: "Building test"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: workflow/nix-shell-action@v3
        with:
          flakes: nixpkgs#nixfmt-rfc-style nixpkgs#gnumake
          script: |
            echo "Loading into shell environment for testing"
            make format-check
            make check
            nix build .#extras
            
            echo "MODs"
            echo "------------------------------"
            ls "$(readlink -f result)/data/mods"
            echo
            echo "SOUNDs"
            echo "------------------------------"
            ls "$(readlink -f result)/data/sound"
            echo
            echo "GFXs"
            echo "-----------------------------"
            ls "$(readlink -f result)/gfx"
            nix log .#extras | cat